// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGhShwKrdxIDDoUuYwfPb6CW7jYxRU3w0',
    appId: '1:468124091838:web:11fd65029766eb7be925ef',
    messagingSenderId: '468124091838',
    projectId: 'fir-auth-project-b5d34',
    authDomain: 'fir-auth-project-b5d34.firebaseapp.com',
    storageBucket: 'fir-auth-project-b5d34.appspot.com',
    measurementId: 'G-1XKFBMZ0FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtTHSmok09uRgRGxLmPlZpUzHV6iFQ8FE',
    appId: '1:468124091838:android:52fed932b9054049e925ef',
    messagingSenderId: '468124091838',
    projectId: 'fir-auth-project-b5d34',
    storageBucket: 'fir-auth-project-b5d34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtVNuv00NSpsbNQBfS47C_z6Q91-HytXA',
    appId: '1:468124091838:ios:babc5442793f3044e925ef',
    messagingSenderId: '468124091838',
    projectId: 'fir-auth-project-b5d34',
    storageBucket: 'fir-auth-project-b5d34.appspot.com',
    iosBundleId: 'com.eusopht.flutterAuthProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtVNuv00NSpsbNQBfS47C_z6Q91-HytXA',
    appId: '1:468124091838:ios:d94314b3ac60c800e925ef',
    messagingSenderId: '468124091838',
    projectId: 'fir-auth-project-b5d34',
    storageBucket: 'fir-auth-project-b5d34.appspot.com',
    iosBundleId: 'com.eusopht.flutterAuthProject.RunnerTests',
  );
}
